### ISSUE TITLE
Feature Request: Add hardware info and 3d printing models

### ISSUE THREAD

**Issue by Profianton** [WRI-Obernburg/PixelMatrix#5]
Hallo Tim,

kannst du bitte auch noch die 3d-Druck Teile und eine Hardware Liste(LED & Microcontroller) hochladen?

Viele Grüße

Anton

**Comment by timarnoldev** [comment]
Hallo Anton,

Ja kann ich gerne noch machen.

Ich werde ich mich auch die Tage an deine Pull Request setzen #4 setzen.
Auch bau ich noch Möglichkeiten ein das Frontend, also die Website, die auf dem Handy aufgeht in Zukunft besser zu erweitern. Ich hätte nicht gedacht, dass das schon so früh gebraucht wird 😅

Grüße
Tim
